### PR TITLE
Va 123 inbox component tests

### PR DESCRIPTION
**Pull request by TishamIslam**
### Description
Test for the Inbox component. Also has some minor miscellaneous changes in code.

### What to test for/How to test
Look at the Inbox component, and point out if there's anything that should be anything else tested.

### CODE REVIEW

**Review by nibivi77 — COMMENTED** [review]
This is great ! I will approve but I have a question. Should we test all other functions from the inbox store module? For example, `getSelectedInboxItem`,  `getSelectedInboxItemId` and `isMobile, etc...`

**Comment by TishamIslam** [comment]
> This is great ! I will approve but I have a question. Should we test all other functions from the inbox store module? For example, `getSelectedInboxItem`, `getSelectedInboxItemId` and `isMobile, etc...`

The store functions are all tested here: 
image

**Comment by nibivi77** [comment]
> > This is great ! I will approve but I have a question. Should we test all other functions from the inbox store module? For example, `getSelectedInboxItem`, `getSelectedInboxItemId` and `isMobile, etc...`
> 
> The store functions are all tested here:
> image

Ah yes of course! Silly me hahaha

**Review by nibivi77 — APPROVED** [review]
This looks very good Tisham! :D

**Pull request merged**
